### ISSUE TITLE
Can’t arrive to add a minihub

### ISSUE THREAD

**Issue by alvanh** [AdyRock/com.switchbot#106]
Hello
I. Have a MINI hub connected to the Cloud.
I’m looking for the procedure to connect the hub to the app

I tried to press the button on the top of the mini herb, and then click get the hub on the app

Nothing show up
Could you please give me the procedure
Thank you

**Comment by AdyRock** [comment]
You can't add the hub to the app, you just add the devices that are connected to it.

**Comment by alvanh** [comment]
Ok
Could you tell me why ?
Or maybe you have a FAQ about it
Thank you

Cordialement
Alexandre Hotton

**Comment by AdyRock** [comment]
The hub doesn't have any properties to see, so nothing to there to add.
If you create remote devices, they are added to Homey as a remote device. Any other device such as bots, curtains, temperature sensors, etc, that you connect to the cloud via the hub are also added as separate devices to Homey.
