### ISSUE TITLE
SwitchBot Hub 2 light sensor in Home Assistant?

### ISSUE THREAD

**Issue by Hans6500** [AdyRock/com.switchbot#109]
The SwitchBot Hub 2 has a light sensor that I like to integrate in Home Assistant so that I can use it to turn on the lights when it gets dark. But I can’t find a way to integrate it. I have managed to integrate the temperature and humidity sensor. It shows up in the SwitchBot app (see picture) but not in HA. 
![IMG_204B62EF36B2-1](https://github.com/AdyRock/com.switchbot/assets/165378938/cd9e08ab-64be-4f0f-8f01-90ece5b69d9c)

**Comment by AdyRock** [comment]
The light sensor is just a boolean light or dark, so only shows up in the device.

**Comment by Hans6500** [comment]
But it has values from 1-20 and not only the Boolean operators like and, or and not? So, I thought it might be possible to create a script like when the value is 5 turn or he lights in the living-room.

**Comment by AdyRock** [comment]
I will look into it. My memory is not as good as it used to be, so I probably made a mistake.

**Comment by AdyRock** [comment]
I have just checked and the light level already uses the measure_luminance capability, but changes the units to %. Not sure what else I can do.

**Comment by Hans6500** [comment]
Thanks AdyRock. I’m using Home Assistant. Can you give me some advice how to integrate this? I have seen that apparently in HomeKit is shows up, but in Home Assistant I can’t find it. The temperature and humidity sensors do, but the light sensor doesn’t.

**Comment by AdyRock** [comment]
Unfortunately I don't use HA, so I don't know.
Maybe ask on the Athom forum as I know there are people on there that use it..

**Comment by Hans6500** [comment]
Ok Adrian, thanks. I will try another forum.
