### ISSUE TITLE
Cant add device in switchbot app

### ISSUE THREAD

**Issue by Backaker** [AdyRock/com.switchbot#11]
When I try to add a device on switchbot app in homey it says "invalid token"
What should I do?
They work fine in Google home and the switchbot app on my phone but not in the switchbot homey app

**Comment by Backaker** [comment]
Ok. And where do I find the readme? I cant find it.As you probably understand, im very new at thisSkickat från min Galaxy
-------- Originalmeddelande --------Från: Adrian Rockall ***@***.***> Datum: 2021-10-14  20:28  (GMT+01:00) Till: "AdyRock/com.switchbot" ***@***.***> Kopia: Backaker ***@***.***>, Author ***@***.***> Ämne: Re: [AdyRock/com.switchbot] Cant add device in switchbot app (#11) 
The instructions for getting the token are in the readme.

**Comment by AdyRock** [comment]
As this seems to resolved I'm closing the issue but please feel free to get back in touch if you have any more problems.
