### ISSUE TITLE
Test Hub2 temperature against a Homey preset variable

### ISSUE THREAD

**Issue by Dune4141** [AdyRock/com.switchbot#119]
In Homey, when temperature changes,
I can test temperature against higher or lower than a value 

I need this test against a Homey variable (that is set by other flows,)

By this way, I can build a room temperature thermostaten that acts on a preset variable.

Please investigate feasibility.

Regards Thomas

**Comment by AdyRock** [comment]
Like this you mean:
<img width="290" alt="image" src="https://github.com/AdyRock/com.switchbot/assets/38184396/4c3ed626-06a9-42c0-8f86-4fa1d8e6d5ac">

**Comment by Dune4141** [comment]
Yes,But than compare to a variable.Met vriendelijke groet,ThomasOp 20 mei 2024 17:03 schreef Adrian Rockall ***@***.***>:
Like this you mean:
image.png (view on web)

**Comment by AdyRock** [comment]
The image is showing a variable, so I don't understand?

**Comment by Dune4141** [comment]
I stand corrected.
I did not know that the label / tag. was meant to retrieve variables, so I could only enter a value myself.

Now I see how it should be done. I am sorry for the confusion.
Thanks.

Please close this thread.

**Comment by AdyRock** [comment]
You're welcome.
