### ISSUE TITLE
No support for Thermometer and Hygrometer Plus

### ISSUE THREAD

**Issue by ronaldotto** [AdyRock/com.switchbot#121]
I think the device is to new?

When adding the Thermometer and Hygrometer Plus to homey, i can select temperature and humidity BLE and HUB.
<img width="197" alt="afbeelding" src="https://github.com/AdyRock/com.switchbot/assets/6816670/906dee94-de51-4466-a4fa-75bdbd470f6c">

With BLE, nothing is detected
With hub, i get the following error:
![afbeelding](https://github.com/AdyRock/com.switchbot/assets/6816670/73fd255a-6233-442c-9711-ff58e663a5b8)

**Comment by AdyRock** [comment]
How do you log into your SwitchBot account?

**Comment by ronaldotto** [comment]
I use e-mail and password. After inspecting some logs, it does seem to be an authentication issue.
In the Homey app there is no way to re-authenticate (as far as i could see)
Removing and re-installing gave me the option to authenticate. Deleting all devices from the Homey, but that were only a few.

**Comment by AdyRock** [comment]
Each SwitchBot device has a repair option. Running that will reauthenticate for all the devices.
Sorry it's a bit late now, but ready for next time. 
FYI, the token expires after 1 year, so you will need to do it again.

**Comment by ronaldotto** [comment]
Thanks!.  This thread might help others. So that is why i put invalid_grant in the subject. Since no support for a device was not the problem, but authentication was.
