### ISSUE TITLE
"Invalid token" for scenes app

### ISSUE THREAD

**Issue by SortOfSmart** [AdyRock/com.switchbot#13]
Thanks again for your help last time. I do have a new issue though (sorry). 

So, I went ahead and bought myself the hub (mini) and a couple of other toys. The switchbot smart bulbs are VERY reasonable prized, so I bought two of them. Only to discover the Homey app doesn't support them (yet?) (My fault, btw! Shouldn't have assumed.)
But ah well, I can at least add a couple of scenes, right? I thought. But I get the "invalid token" message if I try to install the scenes app. Any sage advice? 

Btw they work with the Switchbot app and Google home, so the lamps are fine.

**Comment by AdyRock** [comment]
If you are using the release version then you need to add the API Token into the Configure App screen. The test version asks for it when you pair the scene.

**Comment by SortOfSmart** [comment]
Ah, thanks man! I'm really showing my 'noob-ness' here, aren't I? ;-)

The app works flawless now. Not sure yet if I won't change out the bulbs still, because I was planning on making some flows with them. But at least the scenes work with Google Home as well. I saw the bulbs were quite new in the Switchbot Ecosystem. Are there any plans to add support for them in the Switchbot app for Homey in the near future?

**Comment by AdyRock** [comment]
I have started to add support for the bulbs and have ordered one to test so will have an update soon.

**Comment by SortOfSmart** [comment]
Now that is good news. I'll definitely hold off on buying other bulbs and making clunky routines in Google Home then. I'll wait :-) Keep up the good work. Switchbot has some truly unique products, but I don't think most people want to be limited to just their ecosystem.
