### ISSUE TITLE
Please add support for SwitchBot Indoor/Outdoor Thermo-Hygrometer 

### ISSUE THREAD

**Issue by Francas555** [AdyRock/com.switchbot#130]
Hello,
Please add support for SwitchBot Indoor/Outdoor Thermo-Hygrometer to Homey.
Thanks :)

**Comment by AdyRock** [comment]
It's already supported. Use the Temperature and Humidity driver to include it in Homey.

**Comment by janhal** [comment]
Is it possible to add the absolute humidity reading into Homey (BLE)?
Thanks!

**Comment by AdyRock** [comment]
As far as I am aware, that information is calculated by the SwitchBot server and not available directly via the BLE data.

**Comment by janhal** [comment]
Aha, understood, thanks.
Best regards, Jan

Med vänlig hälsning,
Janne
________________________________
Från: Adrian Rockall ***@***.***>
Skickat: Saturday, August 17, 2024 11:53:45 AM
Till: AdyRock/com.switchbot ***@***.***>
Kopia: janhal ***@***.***>; Comment ***@***.***>
Ämne: Re: [AdyRock/com.switchbot] Please add support for SwitchBot Indoor/Outdoor Thermo-Hygrometer (Issue #130)


As far as I am aware, that information is calculated by the SwitchBot server and not available directly via the BLE data.

**Comment by Francas555** [comment]
Thanks, it works :)
