### ISSUE TITLE
Unable to log in

### ISSUE THREAD

**Issue by danielegarato** [AdyRock/com.switchbot#132]
unable to log in, when I try to add a new device it asks me to authenticate.
If I enter user and password it gives me an incorrect password error (I'm 100% sure I'm entering it correctly) while if I log in using the specific button log in with apple ID the login is successful but then it gives me the error "invalid response code: 190"

I also tried to add the hub from the app settings but it gives me an error in that case too

![IMG_0326](https://github.com/user-attachments/assets/3490ec02-b84f-4bba-ba90-b5af94979046)
![IMG_0327](https://github.com/user-attachments/assets/3dcc204f-a76a-46f1-bbee-230d1602cda7)
![IMG_0328](https://github.com/user-attachments/assets/a28f6702-69b1-430d-9a77-b724b02c79c4)

**Comment by AdyRock** [comment]
How do you normally log in to your SwitchBot account?

Some users have found that enabling the developer mode in the SwitchBot mobile app can solve the error 190 issue.

**Comment by danielegarato** [comment]
I log in to the app via Apple login.

**Comment by danielegarato** [comment]
ok by activating the developer mode everything works. thanks
