### ISSUE TITLE
Errore 400: redirect_uri_mismatch

### ISSUE THREAD

**Issue by ogabicgit** [AdyRock/com.switchbot#133]
I try to add switchbot lock.

**Comment by AdyRock** [comment]
If you are using Google login, then it won't work. You will need to create an account using your email address and transfer your devices to that.
I have pointed out the issue to SwitchBot a long time ago but I haven't received any advice.

**Comment by ogabicgit** [comment]
Ok. Thank you

Il Dom 11 Ago 2024, 14:21 Adrian Rockall ***@***.***> ha
scritto:
