### ISSUE TITLE
Curtain V3 group

### ISSUE THREAD

**Issue by vierlijner** [AdyRock/com.switchbot#136]
I've 2 Curtains V3 devices to move a curtain as a group (synchronised). But in Homey it sees them separately. Is it possible to make a group from this? I can't see it in (advanced) settings. 
Ps. I've them connected by Bluetooth (ble).

**Comment by AdyRock** [comment]
If you control the master curtain, the other side should also move. At least that's how it works for me.

**Comment by vierlijner** [comment]
That is correct.
