### ISSUE TITLE
Official app??

### ISSUE THREAD

**Issue by aswespeak** [AdyRock/com.switchbot#137]
How could this be an officail app?
No way to cennect Curtain 3 via Hub 2.
Neither a linked apple account or switchbot account works.
This is not by far how an official app should work.
Hos the H do you add Curtain (Hub)??

**Comment by aswespeak** [comment]
Hi Adrian,

Since I’m not able to login to my switchbot account in any way thru the Homey app I was a bit overwelmed. It’s usually not the standard for official apps.

However, no, when trying to login via mail I just get ”wrong username/password” I use the correct credentials as I use to login to the Switchbot app on my phone.
When trying the amazon and/or apple login I just got a message saying ”you can know close this window”.
Then Homey says ”No new units found”.
I also can’t connect the Hub 2 thru Matter to Homey but that is another story.

Been using Homey since start (10 years) I had newer had any problems with any apps so well. I apologize for my bad tone.
//Anders

6 sep. 2024 kl. 10:38 skrev Stable-Adrian ***@***.***>:

﻿

I was tempted to close this issue immediately due to the tone of the message, but now I have had a few days to calm down, I hope we can start again on more friendly terms.

First, have you managed to login to your SwitchBot account via Homey using the email option as this should work fine.
If you have, then have you added the Curtain 3 to your account using the SwitchBot mobile app and enabled the cloud option (if it still shows in the options).

**Comment by AdyRock** [comment]
It's unfortunate that you have had problems with the app, but this is not usually the case when logging in using an email address.
There is a known issue with using Google accounts and we are trying to find that.

One thing to double check is that the email address is entered exactly as you registered it as It seems the phone app is not as fussy about letter case as the Web authentication is.

**Comment by aswespeak** [comment]
Hi,
I tried now using capital letter in the beginning of the mail but no luck.
I also have a very easy and short mail adress that I been using for more then 20 years.
I think I have tried to login atleast 10 times using the registered email. And even tried the apple login and amazon login.
Google do I know doesn’t work.
Was reading this days before I wrote a support ticket.

One thing I have noticed is when I login to Switchbot.com using my app account they also have a webaccount. I do have both on the same email and password if there could be some corelation.

Other thing is if I try to restore my password under the ”homey” login page, I never recieve an ”reset” email.
If I try to sign up they say email already exist.
I’m working with IT but this is over my head😂

6 sep. 2024 kl. 16:57 skrev Adrian Rockall ***@***.***>:

﻿

It's unfortunate that you have had problems with the app, but this is not usually the case when logging in using an email address.
There is a known issue with using Google accounts and we are trying to find that.

One thing to double check is that the email address is entered exactly as you registered it as It seems the phone app is not as fussy about letter case as the Web authentication is.

**Comment by AdyRock** [comment]
I feel your pain as I also find it frustrating when this sort of thing happens.
Unfortunately, all the authentication is performed by SwitchBot on there servers, so I have no logs or insights as to what is happening there.
Could you try contacting support via the mobile app and ask them to check your account to see if there is an issue their end?

**Comment by aswespeak** [comment]
Hi,
Yes I will do that. Otherwise I just skip the Homey part and use the inbuilt scheduling, but it’s boring😂
Tnx Adrian.

6 sep. 2024 kl. 18:57 skrev Adrian Rockall ***@***.***>:

﻿

I feel your pain as I also find it frustrating when this sort of thing happens.
Unfortunately, all the authentication is performed by SwitchBot on there servers, so I have no logs or insights as to what is happening there.
Could you try contacting support via the mobile app and ask them to check your account to see if there is an issue their end?

**Comment by AdyRock** [comment]
As I have the same report from some other users over the last couple of days, I have reported it SwitchBot again via my new contacts that Athom have put me in touch with.
I am keeping my fingers crossed that this new collaboration will help sort out these things.

**Comment by AdyRock** [comment]
Could I ask you to try something:

1. Open the SwitchBot app,
2. Select the Profile option at the bottom,
3. Tap on Preferences,
4. Tap on About,
5. Tap on the App Version line until a new line appears called Developer Options (probably 10 to 15 times).

Then try to add a device in Homey and log in.

**Comment by aswespeak** [comment]
Hi,
Did all the steps and didn’t work.
I think Switchbot have a major flaw in their signup process.
When trying to install something thru the Homey app they are asking for username, not emailadress.
Nowhere has this username been set.
When trying to set up a new user, still on the same page, they send a email but none of the emails are recieved. Not in inbox, not in spam.
So as long as I cant get register a username I cant login.

//Anders

10 sep. 2024 kl. 23:40 skrev Adrian Rockall ***@***.***>:

﻿

Could I ask you to try something:

  1.  Open the SwitchBot app,
  2.  Select the Profile option at the bottom,
  3.  Tap on Preferences,
  4.  Tap on About,
  5.  Tap on the App Version line until a new line appears called Developer Options (probably 10 to 15 times).

Then try to add a device in Homey and log in.

**Comment by AdyRock** [comment]
Have you created an account using the SwitchBot mobile app as that's the way to go. Then add the devices via the SwitchBot app. Once you have done that, add add them to Homey using the same login.

**Comment by aswespeak** [comment]
Yes, that’s what I did👍
As soon as I had login in the app I tried to add Curtain (HUB) in Homey and there was where the problem started by not being able to login. I can use them as BLE in Homey without problems but i would like to use them thru the HUB 2.

Well, there’s something strange going on at Switchbot and I have no clue why they do not accept my credentials as they are identical to the app where I can login without any problems.
A bit sad because the products seems nice.

11 sep. 2024 kl. 11:17 skrev Adrian Rockall ***@***.***>:

﻿

Have you created an account using the SwitchBot mobile app as that's the way to go. Then add the devices via the SwitchBot app. Once you have done that, add add them to Homey using the same login.

**Comment by AdyRock** [comment]
Hopeful they will get it sorted soon as I am seeing it more frequently now.

**Comment by AdyRock** [comment]
I have published a new test version that has an updated login system using the new servers.
Could you give that a try to see if it works for you?

**Comment by aswespeak** [comment]
Hi,
When installing V 2.0.0 everything seems fine but when adding a product only official comes up as a choice, not the experimental.
When I choose Swithbot its installing the official app in the background.
Or do I need to add products in another way?
Because after I try to install thru Switchbot I het the ”old” login and the app is no longer 2.0.0

//Anders

25 sep. 2024 kl. 11:35 skrev Adrian Rockall ***@***.***>:

﻿

I have published a new test version that has an updated login system using the new servers.
Could you give that a try to see if it works for you?

**Comment by AdyRock** [comment]
Sorry, I'm confused.
You need to go to the Athom app store, find the SwitchBot app and then add test to the end of the URL and load the page. You will then see on the page a warning about it being experimental, but that's OK. Now install the version 2 app on your Homey.
Once it has installed, add your devices to Homey and log in to your SwitchBot account when prompted during the procedure.

Note: The device must already be added to your account using the SwitchBot mobile app.

**Comment by aswespeak** [comment]
Yes I know:)
V2 Experimental installed on Homey.
But when trying to add a unit on Homey by pressing ”+” you have to choose an app, right?and here only the offical apps shows up even if it’s not installed. I can not choose the experimental 2.0.0 under add unit.



25 sep. 2024 kl. 13:38 skrev Adrian Rockall ***@***.***>:

﻿

Sorry, I'm confused.
You need to go to the Athom app store, find the SwitchBot app and then add test to the end of the URL and load the page. You will then see on the page a warning about it being experimental, but that's OK. Now install the version 2 app on your Homey.
Once it has installed, add your devices to Homey and log in to your SwitchBot account when prompted during the procedure.

Note: The device must already be added to your account using the SwitchBot mobile app.

**Comment by aswespeak** [comment]
Ok, then pls take a look at the attached movie.
Then you understand what I mean. Something is strange.




25 sep. 2024 kl. 14:10 skrev Adrian Rockall ***@***.***>:

﻿

If you have installed the test version, then that is the one that appears in the list of apps when you add a device.

**Comment by AdyRock** [comment]
If you have installed the test version, then that is the one that appears in the list of apps when you add a device.
Unfortunately, Github doesn't process attachments when you reply by email.
You will need to log in to Github and upload the file (if it accepts the file type)

**Comment by aswespeak** [comment]
Yes Sorry Adrian, My Iphone movie is way to large.
I post some pics instead. 
on Iphone it looks like this, V2.0.0 installed and only V2.0.0.
When trying to install device it cant find the Experimental but takes the official from database. Pls see pic.
When choosing the only switchbot app in the list the 1.1.58 installs in the background.
Leaving me with only 1.1.58 installed.
There’s simply no way for me to choose the V 2.0.0 even if it’s installed.
![IMG_5451](https://github.com/user-attachments/assets/90415940-d1cf-4e0f-b9fa-047add30a6e8)

![IMG_5450](https://github.com/user-attachments/assets/53f14bac-0848-4c16-9ff3-9dd14d2d28ff)

**Comment by aswespeak** [comment]
If you install from a PC with Windows you will get the exact same result since it takes the app from the database.

**Comment by AdyRock** [comment]
When you add a device, don't use the search, just scroll down and select the app that's already installed.

**Comment by aswespeak** [comment]
Yes I’m stupid as hell.
Now my Curtains are installed in Homey😃
Tnx Adrian. Now I can go on and purchase more😃

One thing, the HUB it self is not possible to get in Homey?

//Anders

25 sep. 2024 kl. 16:44 skrev Adrian Rockall ***@***.***>:

﻿

When you add a device, don't use the search, just scroll down and select the app that's already installed.

**Comment by AdyRock** [comment]
Not stupid at all. I have reported that search quirk to Athom as it is very misleading.

Hope it goes well from here.

**Comment by ApacheCox** [comment]
> Sorry, I'm confused. You need to go to the Athom app store, find the SwitchBot app and then add test to the end of the URL and load the page. You will then see on the page a warning about it being experimental, but that's OK. Now install the version 2 app on your Homey. Once it has installed, add your devices to Homey and log in to your SwitchBot account when prompted during the procedure.
> 
> Note: The device must already be added to your account using the SwitchBot mobile app.

Holy Sh*t this now login screen just fixed my issue thanks a lot !
