### ISSUE TITLE
Flow explanation fault

### ISSUE THREAD

**Issue by vierlijner** [AdyRock/com.switchbot#142]
For the switchbot curtains the card says the 100% is open and 0% is closed, but it's the other way around. 
![Screenshot_20241022-092142](https://github.com/user-attachments/assets/f6883647-3a07-4ef8-a495-fc5e1f728de9)

**Comment by AdyRock** [comment]
The app uses a standard Homey capability, so the Flow cards are provided by Athom and can't be changed.
However, the device does have an Advance setting that allows you to reverse the direction, so maybe that would be the solution?

**Comment by vierlijner** [comment]
Is this not line 2538 in app.Json, the hint part?

**Comment by AdyRock** [comment]
No, that's my custom one for setting the position at a given speed, which is a copy of the built-in one with an additional parameter. So, yes, I could change that one, but it would then be inconsistent with the standard one that you have shown.

**Comment by vierlijner** [comment]
Thanks
