### ISSUE TITLE
Support for homey bridge

### ISSUE THREAD

**Issue by Pascalvkes** [AdyRock/com.switchbot#16]
So i have the switchbot curtains, and i have the homey bridge. But the app is not available for the bridge. Is there an activity to have the app available for the bridge? It would he really appreciated.

br
Pascal

**Comment by AdyRock** [comment]
The test version works on Homey and the Bridge.
https://homey.app/en-gb/app/com.switchbot/SwitchBot/test/

**Comment by Pascalvkes** [comment]
Yes sir,

It works, thank you so many much.

BR
Pascal

Verstuurd vanaf mijn iPhone
