### ISSUE TITLE
Can’t connect anymore BLT

### ISSUE THREAD

**Issue by whizydev** [AdyRock/com.switchbot#17]
Switchbot was connected with Homey for 1 month, but now stopped working. Reinstalled, but doesnt find switchbot anymore with Bluetooth. Timeout error. How to fix it?

**Comment by AdyRock** [comment]
Have you powered Homey off for a few minutes and then back on again?

**Comment by whizydev** [comment]
Yes already tried. When looking for the switchbot (hub) it finds the devices (but i don’t even have a hub), but with Bluetooth directly it doesnt find it. Really weird

**Comment by AdyRock** [comment]
Does it work using the Switchbot phone app?

**Comment by whizydev** [comment]
Yes works by the app

**Comment by AdyRock** [comment]
Could you send the log from the More > Apps > Switchbot > Configure App screen.

**Comment by whizydev** [comment]
Yes I just sent it

**Comment by aartvanwilgenburg** [comment]
had the same problem , after reinstal several times put the switchbot close to homey with no result. at last reboot the homey ,
homey finds the swithbot  . seems to me that homey stops searching after a few seconds before rebooting.

**Comment by AdyRock** [comment]
I never got the log. Could you set the drop list to "Full Information". Then try to pair the bot and then go back to the log and tap on the green "Send Log" button.

**Comment by AdyRock** [comment]
The auth error is normal as you are not using a hub. 
I am on holiday for 2 weeks now but will look at the log as soon as I can.

**Comment by AndresJoseArbol** [comment]
> The auth error is normal as you are not using a hub. I am on holiday for 2 weeks now but will look at the log as soon as I can.

Thank you very much!
