### ISSUE TITLE
app don't start up

### ISSUE THREAD

**Issue by robindelange** [AdyRock/com.switchbot#2]
i installed the skd3 app with cli on my homey, when its installed I can't fill in the api. when I want to configure it, it keeps loading. so I can't do anything with the app, I have install the app twice and did the PtP on homey, that didn't work.
what can I do?

**Comment by AdyRock** [comment]
The SDK 3 app is the one that's in the Athom store. Have you tried to install from there?
Or did you mean that SDK 2 version?

**Comment by robindelange** [comment]
I didnt know that you can download the app already from the athom store, I had read that it has te be done with the CLI methode.
Know I have download it from the App Store,

Thank you for your quick answer and all the work for the app, i have waited a long time for this!

Kind regards

Robin de Lange

Op 16 feb. 2021, om 19:07 heeft Adrian Rockall <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:



The SDK 3 app is the one that's in the Athom store. Have you tried to install from there?
Or did you mean that SDK 2 version?

**Comment by robindelange** [comment]
Other question, when i close my curtains with the switchbot app the close in preformance, when i close it with homey they close in silent mode.

Can i change this? Otherwise my curtains wont fully close.

Thanks you

Robin

Verstuurd vanaf mijn iPhone

Op 16 feb. 2021 om 19:12 heeft Robin de lange <rardelange@outlook.com> het volgende geschreven:

﻿ I didnt know that you can download the app already from the athom store, I had read that it has te be done with the CLI methode.
Know I have download it from the App Store,

Thank you for your quick answer and all the work for the app, i have waited a long time for this!

Kind regards

Robin de Lange

Op 16 feb. 2021, om 19:07 heeft Adrian Rockall <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:



The SDK 3 app is the one that's in the Athom store. Have you tried to install from there?
Or did you mean that SDK 2 version?

**Comment by AdyRock** [comment]
I will have a look. A parameter is passed in to select the mode, but I thought it was set to use the app setting.
Maybe I will make it an option to toggle.

**Comment by robindelange** [comment]
That would be great. Thanks

Regards

Robin

Verstuurd vanaf mijn iPhone

Op 16 feb. 2021 om 20:22 heeft Adrian Rockall <notifications@github.com> het volgende geschreven:

﻿

I will have a look. A parameter is passed in to select the mode, but I thought it was set to use the app setting.
Maybe I will make it an option to toggle.

**Comment by AdyRock** [comment]
There is an updated version in the store that supports the options to reverse the open / close direction and also select the Motion mode for silent, performance or (I think) last used.

**Comment by robindelange** [comment]
Andrian,

Thanks for the quick help!

I have installed it and test is, the performance, silent,last mode workt, but the reverse open/close direction didnt.
I have 2 switchbots and the go from the middel to the outside open, but when I reverse the direction nothing happens.

Kind regards
Robin de Lange

Op 17 feb. 2021, om 11:15 heeft Adrian Rockall <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:



There is an updated version in the store that supports the options to reverse the open / close direction and also select the Motion mode for silent, performance or (I think) last used.

**Comment by AdyRock** [comment]
Thanks for letting me know. I tested it all on the BLE driver and then copied the changes to the hub driver. Only it seems I missed two key bits that actually do the inversion :-(
Sorry about that. I will post another update soon.

**Comment by robindelange** [comment]
No thanks! I’m only a tester:)

When the other update is installed I will test it again and will send you if it workt.
Thank you for making (this) apps, especially from some users from holland witch are very happy with this app:)

Kind regards.

Robin de Lange

Op 17 feb. 2021, om 18:01 heeft Adrian Rockall <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:



Thanks for letting me know. I tested it all on the BLE driver and then copied the changes to the hub driver. Only it seems I missed two key bits that actually do the inversion :-(
Sorry about that. I will post another update soon.

**Comment by AdyRock** [comment]
Hopefully this is resolved OK. As I haven't heard anything for a while I will assume it is now working so I will close the issue. If you have any further question then please let me know.
