### ISSUE TITLE
Cant controll the switchbot button unit

### ISSUE THREAD

**Issue by margarn** [AdyRock/com.switchbot#20]
Adding the device to homey worked fine. But when i try to press on or off, it doesnt work. I tried beeing very close to the homey pro and i tried resetting and adding the device several times. 

The switchbot app works fine, But it would be so much better to be able to use homey.

Thanks :)

**Comment by margarn** [comment]
I also tried adding the experimental app, but i am unable to add the device on that app..

**Comment by margarn** [comment]
Update: Managed to add the device to the new app after a few more tries. 

Im still unable to controll the switchbot button.

**Comment by AdyRock** [comment]
I believe we are communicating about this on the Homey forum?

**Comment by margarn** [comment]
Yes, thanks again

tir. 15. feb. 2022 kl. 23:05 skrev Adrian Rockall ***@***.***
