### ISSUE TITLE
Homey/Switchbot (device’s cloud service not enabled)

### ISSUE THREAD

**Issue by Ikon79** [AdyRock/com.switchbot#21]
Hi, I paired my curtain with homey via ble, it worked so-so, often very buggy. 
so I bought the SwitchBot mini hub to see if it worked better with that. 
it connected to homey without any trouble, but it doesn’t work at all. I just get this error (device’s cloud service not enabled) when I try anything.

**Comment by AdyRock** [comment]
Have you enabled the cloud service feature in the SwitchBot phone app?
You should see a little cloud icon in the top right corner of the tile. If not then open the tile (this is in the SwitchBot app, not the Homey app) and then tap on 'More'. then tap on the gear in the top right corner of the screen and the on the Cloud Service line. That should open a screen where you can enable the Cloud Services.

**Comment by Ikon79** [comment]
Doh, I’m really really stupid, missed that completely. Works like a charm now, thank you thank you
