### ISSUE TITLE
Can't connect to hub mini, cloud enabled

### ISSUE THREAD

**Issue by pvgent1** [AdyRock/com.switchbot#22]
I've got SwitchBot working in NodeRed using API token. Cloud is enabled.
When i start the Switchbot app in Homey is see in the logging 'server got: Are you there switchbot?'

In detected tab there are no devices when ik click get Hub devices i get 'Error No OAuth2 client Found'

Is de problem that i already have a connection in NodeRed? How can i solve this?

**Comment by AdyRock** [comment]
The message 'server got: Are you there switchbot?' is where the app is checking for my ESP32 modules, so is not related to the SwitchBot hub.

Have you tried to add a device to Homey yet?
The app fetches an authorization token during the pairing process where you will be asked to log into your account. It no longer uses the API token obtained from the SwitchBot phone app as SwitchBot have provided me with an OAuth2 login feature. So I don't think having NodeRed connected should be a problem.

**Comment by pvgent1** [comment]
Typical an user error, i tried to configure the app in Homey. 
I have added the device without a problem to Homey app.
