### ISSUE TITLE
SwitchBot Smart Lock - possibility to connect to Homey?

### ISSUE THREAD

**Issue by xaxamar** [AdyRock/com.switchbot#23]
Hello,
I consider to install a SwitchBot Smart Lock (I think it is WiFi, need a little SmartBot hub), but I'm not sure it can work with Homey via your app. Is it possible?
Kind regards

**Comment by AdyRock** [comment]
I haven't received a lock yet to work with so unfortunately it's not currently supported. 
If you are happy to be a test subject then I can add it from spec so you can feedback issues to me?

**Comment by AdyRock** [comment]
I received the lock from SwitchBot today and I have integrated into the app. Just waiting for some images before I publish the update to test, so hopefully should be ready this week.

**Comment by AdyRock** [comment]
The lock is implemented in the latest test version. However, since last week, SwitchBot broke the ability to control the lock. It was working but not now. There is an issue on the SwitchBot Git repo about it and another user was told it was a mistake and should be fixed.

**Comment by AdyRock** [comment]
The new test version uses the new SwitchBot v1.1 API so Homey can control the lock
