### ISSUE TITLE
Can’t see Switchbot scenes

### ISSUE THREAD

**Issue by bellringer2** [AdyRock/com.switchbot#24]
Hi,

Thank you for this app. It works really well.

I have just discovered one problem which worked fine before.

When I try to add a “then” card to “run a scene” and then I click on “scene name” no scenes are returned for me to select. I definitely have Switchbot scenes and I have existing Homey flows that call these. 

I just can’t create new flow cards.

please help

**Comment by AdyRock** [comment]
That should be fixed in the test version 1.1.6.
Just add \test to the end or the url to install test version:
https://homey.app/en-gb/app/com.switchbot/SwitchBot/test/
