### ISSUE TITLE
switchbot battery levels

### ISSUE THREAD

**Issue by ronwell74** [AdyRock/com.switchbot#25]
Hi i previously had my switchbot button pushers, connected to homey via BLE but wasn't reliable but i liked the battery level on it. I have now moved them to homey via the hub, but I couldn't find where to add the api token. also the battery levels are not there, can I get them back without going back to Ble connection
thanks

**Comment by AdyRock** [comment]
The new app doesn't need the API  token as Switchbot have given access to use OAuth2 login.  So, when you add a device you will see the Switchbot login page and the returns a token. 

Unfortunately, the API doesn't provide battery information. That has been requested but not added yet, so fingers crossed they will get to it at some point.

**Comment by ronwell74** [comment]
thank you. i thought i had missed something.
