### ISSUE TITLE
Manual scenes no longer work after 1.1.8 update in homey

### ISSUE THREAD

**Issue by Monniks** [AdyRock/com.switchbot#26]
After de SwitchBot 1.1.8 homeyapp update, my manual scenes no longer work, fault code “ No OAuth 2 Client Found”
The scenes are no longer visible,when selecting the switchbot flow card “ run a scene”
The scenes do work in the Swichbot App!

**Comment by AdyRock** [comment]
Can you try the latest test version to see if that fixes the problem?

**Comment by Monniks** [comment]
How do I install the latest test version on homey
