### ISSUE TITLE
Homey Bridge + SwitchBot Curtain BLE - connection errors

### ISSUE THREAD

**Issue by DamianPL** [AdyRock/com.switchbot#27]
Hi,

I connected SwitchBot Curtains to the Homey Bridge Gateway directly via BLE.

The connection is lost every few moments, the connection is not working properly. I sent the report through the application.

I also have a Switchbot hub, using its API, the curtains work fine in Homey Bridge

**Comment by AdyRock** [comment]
Have you tried moving the bridge closer to the device. The BLE range on the bridge is not great.

**Comment by AdyRock** [comment]
Ok, distance shouldn't be a problem. To view the log I need to log in to the Switchbot account, which I can only do from my PC, so I will look at it as soon as I can.

**Comment by AdyRock** [comment]
Unfortunately the log shows nothing:
```
Note: this log has been manually submitted by a user.
    Log ID: bcec4f82-0d45-492f-ac25-1781eda8e007

    User Message:
    Disconnect all time

    stdout:
    n/a

    stderr:
    n/a
```

**Comment by AdyRock** [comment]
Have you try rebooting the bridge?

**Comment by DamianPL** [comment]
> Czy próbowałeś zrestartować most?

Yes

**Comment by AdyRock** [comment]
Unfortunately, Homey with the bridge doesn't show my built in diagnostics page so I have no way to see why it is failing. I must admit the BLE is not very good on my Homey bridge and I do get a lot of connection failures. All I can recommend is to connect via the SwitchBot hub.
