### ISSUE TITLE
Guidance wrong way on curtain flow 

### ISSUE THREAD

**Issue by bellringer2** [AdyRock/com.switchbot#28]
Hi

Small bug guidance on hub curtain “then” card. Guidance says “change position to open (100%) closed (0%) or a value in between”.  My thoughts are that fully open is 0% and fully closed is 100%

**Comment by AdyRock** [comment]
The position (windowcoverings_set) capability and the associated flow cards are built in to Homey so have Athom's wording
https://apps-sdk-v3.developer.homey.app/tutorial-device-capabilities.html

**Comment by bellringer2** [comment]
Should I report this to Homey then? It does seem counter-intuitive to measure how open in percentage terms curtains are.

**Comment by AdyRock** [comment]
You could try but I doubt they will change it now as it has been like that for many years.
