### ISSUE TITLE
New feature request

### ISSUE THREAD

**Issue by bellringer2** [AdyRock/com.switchbot#29]
Hi,

This may not be possible, if so apologies.

I would like a “when” card and an “and” card which check the current status of a hub controlled curtain.

Pure laziness I admit but my use case is so I can simply say the name of the curtain to Alexa and then Homey can decide whether to open or close the curtains based on their current status.

This saves me having to add the extra word when I speak to Alexa and it reduces the flows I need to write by half.

It would be awesome if the then card could have a toggle like a light does then I wouldn’t need the when card.

Thanks in anticipation of you looking into this.

**Comment by AdyRock** [comment]
You could use a log card to determine the current position and then set the new position with a then / else:
https://homey.app/f/UKw547/

**Comment by bellringer2** [comment]
Adrian thank you.

I had forgotten all about the logic cards

Of course that solves my use case perfectly.

Sorry I bothered you

Best regards

Peter Bayly

**Comment by AdyRock** [comment]
No problem.
