### ISSUE TITLE
Homey commands no longer work

### ISSUE THREAD

**Issue by Rokoonl** [AdyRock/com.switchbot#30]
Flows sent from Homey to Switchbot are no longer executed. When creating a new flow I get the following error:

![image](https://user-images.githubusercontent.com/108660080/177116888-b325df3f-0c14-4189-9b8e-8563f4c2fca4.png)

(No OAuth2 Client Found).

I'am using a Hub Mini 85 with Switch Bot curtain.

**Comment by AdyRock** [comment]
Can you select one of the SwitchBot devices and use the repair option If you use the Web app the repair option is on the right click menu, in the phone app you need to open the device, select the gear in the top right, then tap on Maintenance and then tap on Try to Repair.
This will ask you to log in to SwitchBot again where it will get fresh access token.
ATM the token expires after 30 days but I have asked SwitchBot to extend this to their maximum of 1 year.
