### ISSUE TITLE
Response 174

### ISSUE THREAD

**Issue by WBDN2** [AdyRock/com.switchbot#31]
Hello! Any commands I send from Homey yoeld response 174 from curtains. I have u rail 2 connected to hub
![314FC260-46FE-448A-BCB5-0B77477E2873](https://user-images.githubusercontent.com/108786581/177483988-b6b613f3-080a-470c-a905-49d0fc65b6b0.jpeg)

**Comment by WBDN2** [comment]
Hello! I looked at the log now in the Switchbot app and found the answer. ”Cloud service disabled”. Enabled cloud service on the bot and now it works.
![67E88E84-DF15-4A13-8AA3-A45D1497616C](https://user-images.githubusercontent.com/108786581/177489054-46d7e92c-cbb6-486c-b1e0-e31c107665ff.jpeg)

**Comment by AdyRock** [comment]
Ah great, thanks for the information. I will add a check to the app for that error code and display a better message.

**Comment by DV76** [comment]
Do I need a SwitchBot hub to turn on cloud service and add to homey?

**Comment by WBDN2** [comment]
Hello!

Yes, I think so. I have the Switchbot mini hub.

**Comment by AdyRock** [comment]
The hub is required for the cloud service but you can use Homey's BLE to connect to devices as well. I think the cloud now works better than Homey's BLE unless you are technical enough to use my ESP32 solution.

**Comment by DV76** [comment]
Thx for quick answer!
I have added the two curtains to Homey BLE but when I press the “button” in Homey I get the code 174 back.

**Comment by AdyRock** [comment]
Could you provide a screenshot of the error?

**Comment by DV76** [comment]
![curtain](https://user-images.githubusercontent.com/108713376/178109130-d0044efe-9743-425b-bd4c-a9b83d9d7762.jpg)

**Comment by AdyRock** [comment]
That looks like the error from the hub device. When you add the curtains to Homey make sure you select Curtains (BLE) to connect with Homey's BLE.

**Comment by DV76** [comment]
Your right! The BLE did not work, I tried it again but just times out when I'm trying to add. Do you have any tips?
Likely I will order the hub 😎

**Comment by AdyRock** [comment]
The hub is probably the easiest way to go. Homey's BLE is a bit hit and miss. I have one Homey that works quite well and another that very rarely works, even though they sit quite close together. However, event the Homey that works well has a shorter range than the SwitchBot hub.
The best solution is to get an ESP32 and load my BLE hub code on to it. That has a good range, is cheaper than a SwitchBot hub and provides instant feedback to Homey. However you would need some technical know-how to get the code on to the ESP32.
