### ISSUE TITLE
Can’t get the app to work

### ISSUE THREAD

**Issue by PimM92** [AdyRock/com.switchbot#4]
When installing 4 Switchbots + Hub, I constantly get “invalid token”.
![BD3CB73F-A606-4A4F-8D29-95D354AC1FCE](https://user-images.githubusercontent.com/82468784/114598265-005a2c80-9c92-11eb-9a0e-268b87d3a31b.png)

**Comment by AdyRock** [comment]
Have you entered the API token in the app configuration page?

**Comment by PimM92** [comment]
@AdyRock thanks! It worked
