### ISSUE TITLE
Double-sided curtain only 1 side works

### ISSUE THREAD

**Issue by MCFurry** [AdyRock/com.switchbot#5]
First of all thanks for putting the effort in this great app! Installation and BLE communication seems to work on first try!
However, whenever I open/close my curtains via homey, only one of the curtains moves.
The two curtain motors are linked together in the switchbot app though, so opening/closing there always activates both. Any clue why this could be? Or what more information I could provide to help you track the problem?

Edit: I just sent a log from your app, but please let me know if anything else is desired!

**Comment by AdyRock** [comment]
Hi,
When you add the curtains to Homey it should find both motors. One of the motors is the independent one and the other is the dual contol one. If you only add one make sure it is the dual control one. The best way to work out which is which is to add both and then operate them. The one that only controls itself can be deleted.

**Comment by MCFurry** [comment]
Aha, I tried once to delete the device and search again but thought it only found one.
I'll try again this evening to see if I can link the other one instead and see what happens then.
Thanks for your swift response!

**Comment by AdyRock** [comment]
It might be they are close to the limit of range (RSSI -76 on the one in the log). You should see both appear in the list together if you don't already have one paired to Homey. If you don't see both then try moving Homey a bit closer.
What Homey version are you using?
Athom made a few BLE improvements in version 6.

**Comment by MCFurry** [comment]
I'm on a Homey (Early 2016) model with latest firmware (6.1.0).

I just sent you another log from the app. When trying to add a device, only one curtain is detected. But looking at the log both curtains are shown. 
The one ending in :96 is the one being detected when 'adding device' and shows an RSSI of -73 in the log.
The one ending in :AE is **not** being detected when 'adding device' and shows an RSSI of -80 in the log.

Is there a threshold in the app to not show the other motor since the signal is weaker? Or is there another reason why it doesn't show when adding a device?

I could of course simply link them in opposite order to hopefully have homey detect the 'master' device instead, but I'm curious why the log shows both devices but the 'adding devices' only shows one?

**Comment by AdyRock** [comment]
I agree it is curious. The information in the log certainly suggests that both should be detected. The app doesn't use the RSSI value to filter, it is just there for information. The only reasons (in theory) for them not being detected is if the ServiceData structure is empty or the device is already in Homey, which is determined by the "id" value.

Was the log data from just after you tried to add the curtains?

**Comment by MCFurry** [comment]
Yes, after a fresh reinstall of the app to be exact, just to be sure. So I guess there shouldn't be any known ID's to Homey?

**Comment by AdyRock** [comment]
Provided you uninstalled first as that will delete all app data. If you just installed it over the top then it retains everything.

**Comment by MCFurry** [comment]
I uninstalled first indeed, then reinstalled, then tried to add a curtain BLE device and then sent you the resulting log.
Anything else I can provide to help you?

**Comment by AdyRock** [comment]
I'm in the process of switching off my ESP32 hub and moving Homey closer to my curtains so I can test it here.
I will let you know if I find anything or need more information.

**Comment by AdyRock** [comment]
Hmm, looks like I have found the problem with the latest version. I will publish a new test version later this evening.

**Comment by MCFurry** [comment]
Alright, glad you've found it so quickly!

**Comment by AdyRock** [comment]
There is a new test version in the store. Hopefully this should allow both curtains to be added.

**Comment by MCFurry** [comment]
Ahh the community store that is for now, but you fixed it! Both curtains now show when trying to add a device.
Thanks for the quick response and fix!
