### ISSUE TITLE
Hub won't connect 

### ISSUE THREAD

**Issue by chrisgoossens** [AdyRock/com.switchbot#6]
Hub won't connect error invalid token how can I fix this.

Thanks

**Comment by AdyRock** [comment]
Have you followed the instructions on the forum to obtain and enter your APU token?

**Comment by chrisgoossens** [comment]
Thanks Adrian I figured it out my self it was the same as android 😊

Op za 19 jun. 2021 14:56 schreef Adrian Rockall ***@***.***>:
