### ISSUE TITLE
Aircon off trigers ON button.

### ISSUE THREAD

**Issue by salbang** [AdyRock/com.switchbot#8]
Aircon remote control usually have separate off button and codes, but homey app triggers ON function when Off is requested. Could you please fix this? Thank you for your work.

**Comment by AdyRock** [comment]
I will look into that this evening.

**Comment by AdyRock** [comment]
Hmm, this is a bit awkward as the API requires all the parameters (temperature, mode, fan and power) to be sent in one command. Therefore the power has to have a state, hence I used a toggle type on/off capability.

**Comment by AdyRock** [comment]
OK, I think I have worked out a better way. I post a test version soon.

**Comment by salbang** [comment]
Thanks. Actually I found that after I toggled the power button to off mode then setting temperature turns off the aircon.

**Comment by AdyRock** [comment]
I have uploaded the test version to the store if you could check it for me.

**Comment by salbang** [comment]
It works well. Thanks for the patch.

**Comment by salbang** [comment]
Turn on/off does not work on flow.

**Comment by AdyRock** [comment]
I have published a new test version that should fix the flow on/off. Let me know if it solves the problem.

**Comment by salbang** [comment]
It works well in the flow.

**Comment by salbang** [comment]
It would be better if you can add power toggle feature when we touch the icon for aircon, tv, scene and etc.

**Comment by AdyRock** [comment]
The problem is the app would need feedback to know what the current state is so the toggle is in the correct state. Unfortunately all remote devices and scenes don't provide that information because the box can only send commands. So, for example, if you turn on the device with the app the button shows it is on. If you then turn it off with the remote control the app wouldn't know and therefore still shows it's on. Then when you toggle it via the icon to switch the icon off, it would send the wrong command, which on some devices would still toggle the power state back to on again.

**Comment by salbang** [comment]
Understood for the power toggling. However, at least for scene, I think just clicking the button execute the scene should be OK. Does homey api not support it for scenes?

**Comment by AdyRock** [comment]
The tile toggle is only available for boolean capabilities (on / off).

**Comment by salbang** [comment]
I see. Thanks for the explanation. I think it is a shame of homey API for not supporting such feature. I think you may release the test version. As far as I've used, I have no problem so far.

**Comment by AdyRock** [comment]
I understand where you are coming from and I have been thinking about this over time (hence taking so long to respond). My concern is a lot of users will not be so understanding of the sync. problem and I will get more reports that is is not working.
I have a floor standing aircon unit and it use the same command for on and off so once that is out of sync. it stays that way unless I use the remote again.
As there is a work around for you and others that understand the problem I am inclined to leave it as it is.
I hate saying no to user request but I think I will for now on this one. If more users ask for this then I will consider it again.
