### ISSUE TITLE
Swichbot 

### ISSUE THREAD

**Issue by oleVicsen** [AdyRock/com.switchbot#86]
Har en swichbot på homey 2023
Fra man trykker på aktivering knap i app går der 6sek før swichbot reagere
Det sammen i flows😪

**Comment by AdyRock** [comment]
Unfortunately that is about as good as it gets. I have interfaced to mine via BLE and a SwitchBot hub and both have a similar response time of 5 to 6 seconds.
Using my own ESP32 based hub takes about 2 seconds of the time, but it is still around 3 seconds.

**Comment by oleVicsen** [comment]
Thank you👍😪😪😪😪😪😪
