### ISSUE TITLE
Curtain 3 not working with Homey

### ISSUE THREAD

**Issue by lucmechelen** [AdyRock/com.switchbot#87]
I bought the new switchbot curtain 3 and switchbot hub mini.
I am not able to connect with homey, but it work with google.
Seems to me that homey app can not correct log in.
Is there support to operate the switchbot curtain 3 with Homey. 
Thank you.

**Comment by AdyRock** [comment]
You need to install the test version from the app store. Just find the app in the store and add/test to the end of the URL.

**Comment by lucmechelen** [comment]
I have installed version 1.1.35, and the test see the  devices.But no connection can be made with homey.LucOp 28 okt 2023 om 11:16 heeft Adrian Rockall ***@***.***> het volgende geschreven:﻿
You need to install the test version from the app store. Just find the app in the store and add/test to the end of the URL.

**Comment by AdyRock** [comment]
Have you enable cloud services for the curtains in the Switchbot app?

**Comment by AdyRock** [comment]
Also, did you use the Hub or BLE device option when you added the curtains to Homey?

**Comment by lucmechelen** [comment]
Yes I enabled cloud services for the curtains, the work with google.LucOp 28 okt 2023 om 14:28 heeft Adrian Rockall ***@***.***> het volgende geschreven:﻿
Have you enable cloud services for the curtains in the Switchbot app?

**Comment by lucmechelen** [comment]
I tried both.I first get the curtains bots and try to connect using BLE.BLE turned out not to work, so i get a hub mini but it is also not working.It has something to do with homey login to the switchbot server, I think.LucOp 28 okt 2023 om 14:30 heeft Adrian Rockall ***@***.***> het volgende geschreven:﻿
Also, did you use the Hub or BLE device option when you added the curtains to Homey?

**Comment by AdyRock** [comment]
Ok, so if you have managed to add the curtains via the hub the login must have worked.
Could you open the app settings page, set the Diagnostics log to Detailed Information, then try to control the curtains. Then go back to the Log page and send the log.

**Comment by lucmechelen** [comment]
I send the logs, but there was no good information, i think.When i restart homey, i get this into the log:* 2023-10-28T14:47:40.752Z!!!!!! Invalid response: No OAuth2 Client Found* 2023-10-28T14:47:40.804Z* ************** App has initialised. **************** 2023-10-28T14:47:41.876Z* server listening 0.0.0.0:1234* 2023-10-28T14:47:42.421Z* server got: Are you there SwitchBot? from 192.168.2.24:1234LucOp 28 okt 2023 om 16:25 heeft Adrian Rockall ***@***.***> het volgende geschreven:﻿
Ok, so if you have managed to add the curtains via the hub the login must have worked.
Could you open the app settings page, set the Diagnostics log to Detailed Information, then try to control the curtains. Then go back to the Log page and send the log.

**Comment by AdyRock** [comment]
Could you try the repair option to see if that fixes it.

**Comment by lucmechelen** [comment]
Where can i find the repair option?LucOp 28 okt 2023 om 17:07 heeft Adrian Rockall ***@***.***> het volgende geschreven:﻿
Could you try the repair option to see if that fixes it.

**Comment by AdyRock** [comment]
If you are using the web app then right click on the device and it's in the popup menu. If you use the phone app then open the device, tap on the gear ⚙️ at the top right, select Maintenance and then repair.

**Comment by lucmechelen** [comment]
Maybe i told it wrong, but i dont have the devices.It appears always empty when i login.LucOp 28 okt 2023 om 18:18 heeft Adrian Rockall ***@***.***> het volgende geschreven:﻿
If you are using the web app then right click on the device and it's in the popup menu. If you use the phone app then open the device, tap on the gear ⚙️ at the top right, select Maintenance and then repair.

**Comment by AdyRock** [comment]
Do you see any errors when you login?
Do you connect to SwitchBot by email address or do you use Google, etc?

**Comment by lucmechelen** [comment]
No error when i log in with my email address, just a empty screen like the screenshot i send you.If i try with google i see the same empty screen, but i think that is normal because switchbot does not know my google account.If i use google home (on ipad) and add switchbot with my email address then the curtains come into google home. Therefore i am almost sure it is a homey problem on login at switchbot.LucOp 28 okt 2023 om 19:09 heeft Adrian Rockall ***@***.***> het volgende geschreven:﻿
Do you see any errors when you login?
Do you connect to SwitchBot by email address or do you use Google, etc?

**Comment by AdyRock** [comment]
Can you check the version of the Homey app. It should be 1.1.39.

**Comment by lucmechelen** [comment]
Euch no, the version i have is 1.1.35.Howe do i get this new version?LucOp 28 okt 2023 om 22:05 heeft Adrian Rockall ***@***.***> het volgende geschreven:﻿
Can you check the version of the Homey app. It should be 1.1.39.

**Comment by lucmechelen** [comment]
Good news, i found the experimental version 1.1.40.I was now able to add the curtians. (See screenshot) I want to thank you for your quick support.LucOp 28 okt 2023 om 22:05 heeft Adrian Rockall ***@***.***> het volgende geschreven:﻿
Can you check the version of the Homey app. It should be 1.1.39.

**Comment by ReneVerwoerd** [comment]
Hi @AdyRock, I'm installing the new Curtain 3 tomorrow. Do I still have to install the test-version of the app? Or is the released version already capable for the new Curtain 3?

And if I have to use the test version: will it automatically update later to the released version? Or do I have to install the released version as well?
