### ISSUE TITLE
Got ! [object Object] error when I use on/off on one of my aircons.

### ISSUE THREAD

**Issue by salbang** [AdyRock/com.switchbot#9]
I've generated diagnosis report. The unique id is 20f63eaa-cb2d-4da8-b398-ae97ad614a1d . Could you please have a look into this problem? Thanks for your work and help.
![IMG_3116](https://user-images.githubusercontent.com/12740762/129312059-46597b69-825e-4f0f-be6a-770da4c8247c.PNG)

**Comment by AdyRock** [comment]
I can't reproduce that one. I have tried switching off the hub and I get a sensible error message.
The diagnostic log is not showing any issues. Could you try enabling the apps log:
More > Apps > SwitchBot > Configure App > Log tab and set the Diagnostic Log to Basic Information.
Then operate the AC so you see the error message. Then go back to the log and tap on Send Log.

**Comment by salbang** [comment]
This problem still persists in the test version. Power off works but power on or temperature setting gives the same error.

**Comment by salbang** [comment]
I got the reason. The aircon does not support auto mode and it is disabled in switchbot app. If I change mode to cool in homey and do jobs like power on and set temperature, then everything is OK.

**Comment by salbang** [comment]
Turn on/off does not work in flow.

**Comment by AdyRock** [comment]
Hopefully all error message should be clearer now, at least in as much as they will show the information I get back in a readable form.
Unfortunately Homey doesn't allow dynamic list so I have to include all the options. Also I can't see any way to get the list of supported features back from SwitchBot.
So for now I can't address the unsupported options.
