### ISSUE TITLE
Add device mini robot k10

### ISSUE THREAD

**Issue by gicro** [AdyRock/com.switchbot#92]
Hello,

Do you allow to add a robot vacuum cleaner device to the application catalog?

To be able to start the robot from homey.

Thanks

Gilles

**Comment by AdyRock** [comment]
I will need to check the API document to see what features are supported.
Do you have a Switchbot hub or do you require direct connection?
The hub/web API is documented but the direct connection isn't, so without a device I can't do much for direct connection.

**Comment by gicro** [comment]
HelloAbsolutely, I understand that you can’t do for the direct connection.I don't have SwitchBot products except the robot I imagined that homey can control this robot via web api like the other devices of this brand.We hope you will find this solution.Thank for your answer quickly.RegardsGilles ***@***.***é de mon iPhoneLe 4 janv. 2024 à 07:48, Adrian Rockall ***@***.***> a écrit :﻿
I will need to check the API document to see what features are supported.
Do you have a Switchbot hub or do you require direct connection?
The hub/web API is documented but the direct connection isn't, so without a device I can't do much for direct connection.

**Comment by darrelletherington** [comment]
Hi
Is there any update on this?  I assume sevral features would be available to flowcards as it does have a number of features available via IFTTT but would be good to control direct from Homey Advanced Flow?
Thanks
Darrell

**Comment by darrelletherington** [comment]
> I will need to check the API document to see what features are supported. Do you have a Switchbot hub or do you require direct connection? The hub/web API is documented but the direct connection isn't, so without a device I can't do much for direct connection.

Hi
Just checking to see if any progress on this or if there is any alternative way to add the K10+ into Homey Pro - the new vacuum is proving very popular so I'm sure it would be a good addition to the App?
Thanks
Darrell

**Comment by AdyRock** [comment]
Sorry, I've not had time to look into this yet.

**Comment by darrelletherington** [comment]
Ok, thanks for updating is.

 

Also, great App, happy to make a donation to ongoing development and if I can help in anyway with testing the K10+, please let me know – very happy to try experimental versions.

Thanks

Darrell

**Comment by AdyRock** [comment]
I have started to look into this and see that the API document only lists the S1 and S1 Plus, so I'm not sure if this is the same as the K10.
So I can see what is reported could someone send me the detected log from there Homey Pro?
Open the app settings page, tap on Get Hub Devices, wait for the list to fill and then tap on Send Log.

**Comment by AdyRock** [comment]
Unfortunately, GitHub doesn't support attachments via email replies, you will need to login to GitHub and upload the image to a new comment.

**Comment by darrelletherington** [comment]
Ahh ok, I think it will be same as the log anyway so you should have that via Homey.  Let me know if received ok?

Thanks

Darrell

**Comment by AdyRock** [comment]
In the app settings there is also a tab for Get Status, could you copy the deviceId from the device list and then paste that into the Get Status tabs Device ID field. Then tap on Read Status and send that log. That will show me the reported properties.

**Comment by darrelletherington** [comment]
Adrian

All done, you should have it now.

 

{

  "deviceId": "360TY420703022324",

  "deviceType": "WoSweeperMini",

  "workingStatus": "ChargeDone",

  "onlineStatus": "online",

  "battery": 100

}

 

Thanks

Darrell

**Comment by AdyRock** [comment]
Yep, got all that thank you. Hopefully should be in a test version later today.

**Comment by darrelletherington** [comment]
Adrian

That’s brilliant news, let me know and I’ll give it a full test.

 

One thing I forgot to mention but I suspect looking at properties is not possible is on the iOS App there is an option to select room you want to clean but it is not available for scene or exposed to Alexa so guessing not available outside the App but if it was possible to include in a flow it would be excellent.

 

Thanks for all your support.

Darrell

**Comment by AdyRock** [comment]
New test version is in the store.
It has all the available options, so room is not in the API.

**Comment by darrelletherington** [comment]
Adrian

Looks brilliant so far.  A couple of comments below that may or may not be possible but would add value if possible.

 

When

Vacuum State Changed – could this be a drop down to what the state has changed to? (be useful for adding timeline entries as you don’t know in advance what states are available – I can work them out but maybe useful for less tech users?)

 

And

Could there be a “And Vacuum stat is” ??  would be useful

 

Then

Start – works perfectly

Stop – works perfectly

Dock – fails, message “card errored after 8ms” Error: Flow Card not registered (type: action, id: dock)

Set power – still testing

 

Thanks again, brilliant work.

Darrell

**Comment by darrelletherington** [comment]
Battery status works perfectly in app too.

Thanks.

**Comment by darrelletherington** [comment]
Use this

https://homey.app/en-gb/app/com.switchbot/SwitchBot/test/

**Comment by gicro** [comment]
Thank for quickly. I test now.

**Comment by AdyRock** [comment]
There will be a new test version in a minute with the bug fixed and the new requests added

**Comment by AdyRock** [comment]
It's in the store now, so let me know how it goes.

**Comment by gicro** [comment]
Work without hub switchbot :) 
I just ordered the action of cleaning and returning to the station. I will test it again. I'll come back if I have a remark.

For the information, I activated the API option from the SWITCHBOT application as I followed the instructions on this link https://github.com/OpenWonderLabs/SwitchBotAPI. 

If we can pilot the K10 robot without using SwitchbotAPI?

Thank you for everything.
Gilles

**Comment by AdyRock** [comment]
I guess it uses WiFi to connect directly to the Switchbot cloud.

**Comment by darrelletherington** [comment]
One small bit on state, says “clearing”, should this be “cleaning”?

 

Also, just tried trigger on state change to “Clearing” in advanced flow and didn’t trigger but variable did change so may be the Homey, will do some more checks.

Darrell

**Comment by AdyRock** [comment]
I did wonder that myself, so copied and pasted the value from the API document. 
It is possibly a spelling error in there, but as I don't have a device I could only go with it. 
If you can say for sure it's cleaning then I will change it and report the error to SwitchBot.

**Comment by darrelletherington** [comment]
Just checked app on iPhone and all references are clean or cleaning so think must be typo.Darrell Best regards Darrell EtheringtonTelephone: +44 7768 107111On 16 Feb 2024, at 17:59, Adrian Rockall ***@***.***> wrote:﻿
I did wonder that myself, so copied and pasted the value from the API document.
It is possibly a spelling error in there, but as I don't have a device I could only go with it.
If you can say for sure it's cleaning then I will change it and report the error to SwitchBot.

**Comment by AdyRock** [comment]
OK, I have changed the clearing to cleaning and will report the error that's in the API documents.
New test version is now in the store.

**Comment by darrelletherington** [comment]
Ok thanks, I’ll try and test all cards tomorrow and let you know.Best regards Darrell EtheringtonTelephone: +44 7768 107111On 16 Feb 2024, at 19:52, Adrian Rockall ***@***.***> wrote:﻿
OK, I have changed the clearing to cleaning and will report the error that's in the API documents.
New test version is now in the store.

**Comment by darrelletherington** [comment]
Hi Adrian

Fab work on this, couple more bits I’ve found during testing but nothing major:

 

*	In Homey App on iOS, if you select “Power Level Quiet” – you get the red banner “missing capability listener”
*	In Homey App on iOS, status still shows clearing and not cleaning
*	In Homey App on iOS, charging complete shows as ChargeDone
*	Flow cards for state changed to Charging or state change to Fully Charged do not seem to trigger
*	There is a state in flow card dropdown shown as Dormat – is this correct? Assume it might be dormant? But still not sure what it would be as all other states are covered

 

Also, an observation, in the setup for SwitchBot App I couldn’t see an obvious place to enter account credentials or is this just because it is experimental version?  Mine had somehow got lost but found the option on the device settings un try to repair may be by design I guess but might be confusing for less techy users? 

 

Thanks again.

Darrell

 

 

 

Vacuum Status in iOS App shows Clearing not Cleaning

**Comment by AdyRock** [comment]
Interesting, the status is a text field that just shows that value that is returned by the API, so it seems clearing is not a typo in the document. I will double check dormat again, but I copied and paste the values from the document. 

Account details are entered the first time a device is added and then the token is remembered. This is the way Athom want it to be and the app uses the standard OAUTH2 implementation. Also, Homey cloud has no app settings, so the only way to enter anything is via a device. 

I will check the quiet setting.

**Comment by darrelletherington** [comment]
Adrian

Understood on the OAUTH2, I think mine somehow lost the token when upgrading App but no worries.  It is weird on the clearing bit as SwitchBot’s App refers to it as Cleaning.  Let me know if you want to me test anything, I’m away for a couple of days but can do a full test of all cards when I’m back if you make any changes.

Thanks

Darrell

**Comment by darrelletherington** [comment]
Hi Adrian

Sorry, I had to take an urgent trip away so didn’t get chance to do any more testing.  I’m back now so will do that in next day or so.  I’ll create a flow to test all cards and let you know how it goes.

Thanks again.

Darrell

**Comment by darrelletherington** [comment]
Hi Adrian

Sorry for late reply, been away for a few days but back now and did a bit more testing, I think I found out why my flows were not working and in fact the ‘when’ card for state changed still shows charging even after vacuum has started.  It seems to be there is a variable called ‘state’ (shown on the when card) and also a variable called ‘status’ (available on a then card).  The status one does seem to reflect what the vacuum is doing i.e. charging, cleaning etc.  Does this make sense?

 

Also, it does still say clearing on status variable and not cleaning as it does in the App.

 

I’ll continue testing and feedback but thanks again for adding this.

Darrell

**Comment by darrelletherington** [comment]
Sorry, I meant to attached the screen grab too showing the overlap of the two variables – this grab was taken while the vacuum is cleaning.

 



 

From: Darrell Etherington ***@***.***> 
Sent: Tuesday, March 5, 2024 4:56 PM
To: 'AdyRock/com.switchbot' ***@***.***>; 'AdyRock/com.switchbot' ***@***.***>
Cc: 'Comment' ***@***.***>
Subject: RE: [AdyRock/com.switchbot] Add device mini robot k10 (Issue #92)

 

Hi Adrian

Sorry for late reply, been away for a few days but back now and did a bit more testing, I think I found out why my flows were not working and in fact the ‘when’ card for state changed still shows charging even after vacuum has started.  It seems to be there is a variable called ‘state’ (shown on the when card) and also a variable called ‘status’ (available on a then card).  The status one does seem to reflect what the vacuum is doing i.e. charging, cleaning etc.  Does this make sense?

 

Also, it does still say clearing on status variable and not cleaning as it does in the App.

 

I’ll continue testing and feedback but thanks again for adding this.

Darrell

**Comment by AdyRock** [comment]
Unfortunately GitHub doesn't support email attachments, so you will need to go to the issue and insert the image.

**Comment by gicro** [comment]
Hello
Is it normal that we can no longer use cloud connection to operate the K10 vacuum robot because the test mode application for Homey is disappearing today?

thank
Gilles

**Comment by AdyRock** [comment]
I submitted the test app for review today, so maybe that has caused an issue.

**Comment by Pehbor1** [comment]
Hi,

I'm trying to connect my mini K10+ to Homey. 

I have the Hub2 and the K10 installed in the switch it app. In the Homey app I can see both devices when I press Get Hub Devices. If I try to get status on the device id it only says error. 

And when I try to add a device the app says no new devices found. 

Any lead to so you have a step by step manual to see if I missed something.

Help very appreciated.

**Comment by AdyRock** [comment]
Could you send the Log?

**Comment by Pehbor1** [comment]
Hi,

Log sent.



Skickat från Outlook för iOS<https://aka.ms/o0ukef>
________________________________
Från: Adrian Rockall ***@***.***>
Skickat: Tuesday, June 18, 2024 10:27:30 PM
Till: AdyRock/com.switchbot ***@***.***>
Kopia: Pehbor1 ***@***.***>; Comment ***@***.***>
Ämne: Re: [AdyRock/com.switchbot] Add device mini robot k10 (Issue #92)


Could you send the Log?

**Comment by darrelletherington** [comment]
Hi 

I’m away at the moment but thought I’d check my Homey and saw I had an error too although mine is not connected via Hub, just via Cloud/Wi-Fi.  Not sure if something changes recently but I got the following message.  If anything I can do top help while away (or back home next weekend), let me know.

Cheers

Darrell

**Comment by Pehbor1** [comment]
Hi,

Grusa that mine is wifi connected as well. I got no other option when I set it up. Thought that you always needed a hub? But that might be the standard hub? I bought the hub2.

Skickat från Outlook för iOS<https://aka.ms/o0ukef>
________________________________
Från: darrelletherington ***@***.***>
Skickat: Wednesday, June 19, 2024 2:07:55 AM
Till: AdyRock/com.switchbot ***@***.***>
Kopia: Pehbor1 ***@***.***>; Comment ***@***.***>
Ämne: Re: [AdyRock/com.switchbot] Add device mini robot k10 (Issue #92)


Hi

I’m away at the moment but thought I’d check my Homey and saw I had an error too although mine is not connected via Hub, just via Cloud/Wi-Fi. Not sure if something changes recently but I got the following message. If anything I can do top help while away (or back home next weekend), let me know.

Cheers

Darrell

**Comment by AdyRock** [comment]
The hub is required for all the BLE devices, but devices that support wifi don't use it.

**Comment by Pehbor1** [comment]
Okej, so the Wifi devices should just direct connect to the app in Homey or are they not supported. Reading back it seems like it should be working?

Skickat från Outlook för iOS<https://aka.ms/o0ukef>
________________________________
Från: Adrian Rockall ***@***.***>
Skickat: Thursday, June 20, 2024 4:02:41 PM
Till: AdyRock/com.switchbot ***@***.***>
Kopia: Pehbor1 ***@***.***>; Comment ***@***.***>
Ämne: Re: [AdyRock/com.switchbot] Add device mini robot k10 (Issue #92)


The hub is required for all the BLE devices, but devices that support wifi don't use it.

**Comment by AdyRock** [comment]
I have just realised you have the K10+. The SwitchBot documents don't specifically list that model yet, so it may not be supported by the API, but I have now published an update to the app so it will be recognised.

**Comment by darrelletherington** [comment]
Hi

Just travelling back home, will test this weekend and let you know, thanks for update and continued support.

Cheers

Darrell

**Comment by darrelletherington** [comment]
Hi Adrian

Been meaning to email you for a while but have noticed I almost daily get “Invliad Token” when selecting the K10 in the Homey App, I assume it looses its login but not sure why so frequently.

 

I have also just purchased the K10+ Pro (I blame Amazon Prime days!!!) which is the upgraded one and supports Matter, do you know if you app supports this version as I plan to swap them over at the weekend?  I’m not sure yet if it will connect to Homey Pro via Matter or via Wi-Fi – hopefully it will be my first Matter device to test.

 

Cheers

Darrell

**Comment by AdyRock** [comment]
How is it going with the K10+ Pro, did it work?
If not can you send the logs again so I can see what it reports as I don't trust the API document because some others details have been wrong.

**Comment by Pehbor1** [comment]
Works perfect!

Thanks

Skickat från Outlook för iOS<https://aka.ms/o0ukef>
________________________________
Från: Adrian Rockall ***@***.***>
Skickat: Thursday, October 24, 2024 11:13:11 PM
Till: AdyRock/com.switchbot ***@***.***>
Kopia: Pehbor1 ***@***.***>; Comment ***@***.***>
Ämne: Re: [AdyRock/com.switchbot] Add device mini robot k10 (Issue #92)


How is it going with the K10+ Pro, did it work?
If not can you send the logs again so I can see what it reports as I don't trust the API document because some others details have been wrong.

**Comment by darrelletherington** [comment]
Hi Adrian

Sadly for me, a very bad experience and that’s before I’ve added it to Homey Pro.  I’ve just written a lengthy email due to the limitations of the new Pro (which apparently they are aware of).  Multiple issues with failing on short carpet where the K10+ non pro worked seamlessly, failure to use the new sensor to properly identify table legs and increase suction etc.  I’ve just replied and requested a full refund as it is not fit for purpose with many failings – feels like they rushed this to market as a more advanced unit without proper testing and have admitted there is a number of limitations which they don’t publish on their website!!

 

I shall be returning to my K10+ which works brilliantly.

 

The only issue I have is in Homey Pro, almost every other day, I get token has expired and I have to relink the unit – any ideas on this issue?

Thanks

Darrell
