### ISSUE TITLE
Add Thermometer W3400010 Homey Pro

### ISSUE THREAD

**Issue by biginski** [AdyRock/com.switchbot#94]
Is it possible to add device to the Homey Pro app? It’s Impossible to connect it direct through BTE.
Thanks.

**Comment by AdyRock** [comment]
That is already available in the app.
If you are not able to add it then it could be that you haven't initialised it with the SwitchBot mobile app or It is not in range.

**Comment by biginski** [comment]
Hi Adrian. Thanks for your message. In the Homey app is this device Notting aviable. It is the outdoor version and only two indoor versions are aviable.
Installation in the Switchbot app was easy. The device is there active. But can’t install it in Homey Pro, also not when I try it as one of the indoor devices (ble)

**Comment by AdyRock** [comment]
It would use the Temperature & Humidity  (BLE) device, the same as the indoor device.

**Comment by AdyRock** [comment]
I have 3 of these in Homey using BLE.

**Comment by biginski** [comment]
Yes, it works. After installing in the app I used the installation button again. That was what I was doing wrong. Homey connects with the app, and then ik works.
After I saw your pictures I was convinced that it must work, and is does. Thanks!
Nice temp outside! :-)
