### ISSUE TITLE
Hub mini 90

### ISSUE THREAD

**Issue by ruben9094** [AdyRock/com.switchbot#95]
Hub mini 90 is setup for airco remote and is working perfectly fine in the switchbot app.
When sending commands through homey the airco doesn’t respond.
Any idea on where to start looking dor errors?

**Comment by AdyRock** [comment]
Could you enable the log in the app settings page, then operate the AC from Homey and then go back to the Log page and Send the log.

**Comment by ruben9094** [comment]
> Could you enable the log in the app settings page, then operate the AC from Homey and then go back to the Log page and
