### ISSUE TITLE
(Homey) No updates Temperature sensors

### ISSUE THREAD

**Issue by Franky7471** [AdyRock/com.switchbot#98]
I have both the "indoor/outdoor thermo-hydrometer" sensors, aswell as a Thermometer and Hydrometer Plus sensor, both only show the last measured value after adding it in the Homey-app. So if the temperature changes, it shows in the switchbot app, but not in the Homey app. Whike the "Hub Mini" I use (also switchbot) that I use as a remote for my heater does seem to work.

**Comment by AdyRock** [comment]
Are you connected to them via the hub or via BLE?

**Comment by Franky7471** [comment]
I'm connected via the hub

**Comment by AdyRock** [comment]
Can you make sure the hub is within range of the sensors. To verify that your phone is connecting via the hub, switch off Bluetooth and then check in the Switchbot app.

**Comment by Franky7471** [comment]
For some reason it started working in the middle of the night and it updates now (with a slight delay but that's expected) thanks for the help anyways.
